# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab91ebbd73929b1369c96be24346eda824c4e583ef45aef17e21ad83a96e9d2c86d82e27f6fcc735f94e620d43955790b729b4793e59f7243db84c632c00887f

test:
  secret_key_base: a787465276b07ec86c68f1ab425cd62a4462db5b89bb0e68c56df050910928bd356077d233fa97ba4b968145ba58d1afd0f4222a061a1cba2577ae74480d7f26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
